<?php

/**
 * Author S Brinta<brrinta@gmail.com>
 * Email: brrinta@gmail.com
 * Web: https://brinta.me
 * Do not edit file without permission of author
 * All right reserved by S Brinta<brrinta@gmail.com>
 * Created on : May 19, 2018, 9:29:13 AM
 */
class Brt {

    private $ci;
    public $statesList = [
        "FL" => "Florida",
        "RFL" => "R Florida",
        "GA" => "Georgia",
        "RGA" => "R Georgia",
        "LA" => "Louisiana",
        "RLA" => "R Louisiana",
        "OH" => "Ohio",
        "ROH" => "R Ohio",
        "MA" => "Massachusetts",
        "RMA" => "R Massachusetts",
        "TX" => "Texas",
        "RTX" => "R Texas",
        "CA" => "California",
        "RCA" => "R California",
        "NC" => "North Carolina",
        "RNC" => "R North Carolina",
        "NJ" => "New Jersey",
        "RNJ" => "R New Jersey",
        "CO" => "Colorado",
        "RCO" => "R Colorado",
        "PA" => "Pennsylvania",
        "RPA" => "R Pennsylvania",
        "IN" => "Indiana",
        "RIN" => "R Indiana"
    ];
    public $stateColumnNumbers = [
        "FL" => [
            "preSortDate" => "N",
            "fName" => "B",
            "lName" => "D",
            "contactID" => "E",
            "company" => "F",
            "address" => "I",
            "city" => "R",
            "state" => "S",
            "zip" => "T"
        ], "GA" => [
            "preSortDate" => "N",
            "fName" => "B",
            "contactID" => "E",
            "company" => "F",
            "address" => "I",
            "city" => "R",
            "state" => "S",
            "zip" => "T"
        ], "LA" => [
            "preSortDate" => "L",
            "fName" => "B",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "OH" => [
            "preSortDate" => "L",
            "fName" => "B",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "MA" => [
            "preSortDate" => "L",
            "fName" => "B",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "TX" => [
            "preSortDate" => "L",
            "fName" => "B",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "CA" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "NC" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "NJ" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "CO" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "PA" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "IN" => [
            "preSortDate" => "L",
            "fName" => "B",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ],
        "RFL" => [
            "preSortDate" => "N",
            "contactID" => "E",
            "company" => "F",
            "address" => "I",
            "city" => "R",
            "state" => "S",
            "zip" => "T"
        ], "RGA" => [
            "preSortDate" => "N",
            "contactID" => "E",
            "company" => "F",
            "address" => "I",
            "city" => "R",
            "state" => "S",
            "zip" => "T"
        ], "RLA" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "ROH" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "RMA" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "RTX" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "RCA" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "RNC" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "RNJ" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "RCO" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ], "RPA" => [
            "preSortDate" => "L",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ],
        "RIN" => [
            "preSortDate" => "L",
            "fName" => "B",
            "contactID" => "C",
            "company" => "D",
            "address" => "G",
            "city" => "P",
            "state" => "Q",
            "zip" => "R"
        ]
    ];
    public $stateColumns = [
        "FL" => [
            "preSortDate" => "Pre Sort Date",
            "fName" => "First Name",
            "lName" => "Last Name",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "GA" => [
            "preSortDate" => "Pre Sort Date",
            "fName" => "First Name",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "LA" => [
            "preSortDate" => "Pre Sort Date",
            "fName" => "Name",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "OH" => [
            "preSortDate" => "Pre Sort Date",
            "fName" => "Name",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "MA" => [
            "preSortDate" => "Pre Sort Date",
            "fName" => "Name",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "TX" => [
            "preSortDate" => "Pre Sort Date",
            "fName" => "Name",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "CA" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "NC" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "NJ" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "CO" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "PA" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "IN" => [
            "preSortDate" => "Pre Sort Date",
            "fName" => "Name",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ],
        "RFL" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "RGA" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "RLA" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "ROH" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "RMA" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "RTX" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "RCA" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "RNC" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "RNJ" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "RCO" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "RPA" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ], "RIN" => [
            "preSortDate" => "Pre Sort Date",
            "fName" => "Name",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip"
        ],
    ];

    public function __construct() {
        $this->ci = &get_instance();
    }

    public $permissionColumns = [
        "brm" => ["all", "add", "edit", "delete", "bulk"],
        "nonBrm" => ["all", "add", "edit", "delete", "bulk"],
        "mailing" => ["all", "add", "edit", "delete", "bulk"],
        "checks" => ["all", "add", "edit", "delete", "bulk"],
        "prospects" => ["all", "add", "edit", "delete", "bulk"],
        "orders" => ["all", "add", "edit", "delete", "bulk"],
        "customers" => ["all", "add", "edit", "delete", "bulk"],
        "expenses" => ["all", "add", "edit", "delete", "bulk"],
        "dashboard" => ["all", "stats", "link", "details"],
        "fictitious" => ["all", "add", "edit", "delete", "bulk", "order", "customers", "refund"],
        "refunds" => ["all", "add"],
        "checks" => ["all", "add"],
        "vendors" => ["all", "add", "edit", "delete"],
        "jobs" => ["all", "add", "edit", "delete", "markAsComplete"],
        "deposits" => ["all", "add", "edit", "delete"],
        "reports" => ["all", "general", "state PnL", "fictitious PnL", "pmtQtyReport", "acReports", "ordersReport", "proDocReport", "conversionRateReport"],
        "annualCompliance" => ["all", "add", "edit", "delete", "bulk",
            "orders", "orderAdd", "orderEdit", "orderDelete",
            "customers", "customerAdd", "customerEdit", "customerDelete",
            "refunds"],
        "proDoc" => ["all", "add", "edit", "delete", "bulk",
            "orders", "orderAdd", "orderEdit", "orderDelete",
            "customers", "customerAdd", "customerEdit", "customerDelete",
            "refunds"],
        "bulkDelete" => ["all"]
    ];
    public $brmColumns = [
        "FL" => "Florida",
        "GA" => "Georgia",
        "LA" => "Louisiana",
        "OH" => "Ohio",
        "MA" => "Massachusetts",
        "TX" => "Texas",
        "CA" => "California",
        "NC" => "North Carolina",
        "NJ" => "New Jersey",
        "CO" => "Colorado",
        "PA" => "Pennsylvania",
        "IN" => "Indiana",
        "MIA" => "Miami",
        "BRO" => "Broward",
        "HIL" => "Hillsborough",
        "LAC" => "Lake County",
        "SAR" => "Sarasota",
        "acFL" => "Annual Florida",
        "acNC" => "Annual North Carilina",
        "acNJ" => "Annual New Jersey",
        "acGA" => "Annual Georgia",
        "FIC" => "Fictitious"
    ];

    /*     * ********************************** AC ************************************** */
    public $ACstatesList = [
        "FL" => "Florida",
        "NC" => "North Carolina",
        "NJ" => "New Jersey",
        "GA" => "Georgia",
    ];
    public $ACbrmColumns = [
        "FL" => "Florida",
        "NC" => "North Carolina",
        "NJ" => "New Jersey",
        "GA" => "Georgia",
    ];
    public $ACstateColumns = [
        "FL" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip",
            "amount" => "Amount",
            "fee" => "Fee",
            "cost" => "Cost"
        ], "NC" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip",
            "amount" => "Amount",
            "fee" => "Fee",
            "cost" => "Cost"
        ], "NJ" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip",
            "amount" => "Amount",
            "fee" => "Fee",
            "cost" => "Cost"
        ],
        "GA" => [
            "preSortDate" => "Pre Sort Date",
            "contactID" => "Contact ID",
            "company" => "Company",
            "address" => "Address",
            "city" => "City",
            "state" => "State",
            "zip" => "Zip",
            "amount" => "Amount",
            "fee" => "Fee",
            "cost" => "Cost"
        ]
    ];
    /*     * ********************************************************************************* */
    public $proDocState = [
        "MIA" => "Miami",
        "BRO" => "Broward",
        "HIL" => "Hillsborough",
        "LAC" => "Lake County",
        "SAR" => "Sarasota",
    ];
    public $proDocStateColumns = [
        "MIA" => [
            "name" => "fname",
            "saleDate" => "mname",
            "yearBuilt" => "lname",
            "contactID" => "contactid",
            "salePrice" => "company",
            "landSqFt" => "urbanization",
            "address" => "address",
            "city" => "city",
            "zip" => "zip",
            "state" => "state",
            "preSortDate" => "presortdate",
            "granter" => "grantor(seller)",
            "siteAddress" => "siteaddress",
            "bedRoom" => "bedrooms",
            "bath" => "baths",
            "actualSqFT" => "ActualSqFt"
        ],
        "BRO" => [
            "name" => "fname",
            "saleDate" => "mname",
            "yearBuilt" => "lname",
            "contactID" => "contactid",
            "salePrice" => "company",
            "landSqFt" => "urbanization",
            "address" => "address",
            "city" => "city",
            "zip" => "zip",
            "state" => "state",
            "preSortDate" => "presortdate",
            "granter" => "salesin",
            "legalLine" => "legalline",
            "siteAddress" => "address concatinated",
            "bedRoom" => "beds",
            "bath" => "baths",
            "actualSqFT" => "bldg"
        ],
        "HIL" => [
            "contactID" => "contactid",
            "address" => "address",
            "city" => "city",
            "zip" => "zip",
            "state" => "state",
            "preSortDate" => "presortdate",
            "siteAddress" => "siteaddress",
            "bedRoom" => "bedrooms",
            "bath" => "bathrooms",
            "yearBuilt" => "yearbuilt",
            "saleDate" => "saledate",
            "salePrice" => "saleprice",
            "name" => "company",
            "landSqFt" => "totalheatedAreasqft",
            "actualSqFT" => "totalgrossareasqft",
            "granter" => "totalbuildingvalue",
            "legalLine" => "neighbourhood",
            "propertyType" => "propertytype",
            "siteCity" => "sitecity",
            "siteZip" => "sitezip"
        ],
        "LAC" => [
            "contactID" => "contactid", //
            "address" => "address", //
            "city" => "city", //
            "zip" => "zip", //
            "state" => "state", //
            "preSortDate" => "presortdate", //
            "siteAddress" => "site address",
            "bedRoom" => "Beds", //
            "bath" => "1/2 Baths", //
            "yearBuilt" => "Year Built", //
            "saleDate" => "Sale Date", //
            "salePrice" => "Sale Price", //
            "name" => "company", //
            "landSqFt" => "Land Size (Square Feet)", //
            "actualSqFT" => "Heated Area", //
            "legalLine" => "Full Baths", //
            "propertyType" => "Detailed Property Type"//           
        ],
        "SAR" => [
            "contactID" => "contactid", //-
            "address" => "address", //-
            "city" => "city", //-
            "zip" => "zip", //-
            "state" => "state", //-
            "preSortDate" => "presortdate", //-
            "siteAddress" => "Situs Address", //-
            "bedRoom" => "Bedrooms", //-
            "bath" => "Baths", //-
            "yearBuilt" => "Year Built", //-
            "saleDate" => "Last Sale Date", //-
            "salePrice" => "Last Sale Amount", //-
            "name" => "company", //-
            "landSqFt" => "Living Area", //
            "actualSqFT" => "Gross Building Area", //
            "legalLine" => "Taxable Value" //
        ]
    ];
    public $proDocStateShowColumns = [
        "MIA" => [
            "preSortDate" => "PreSortDate", //"presortdate",
            "saleDate" => "Sale Date", //"mname",
            "contactID" => "ContactID", //"contactid",
            "name" => "Name", //"fname",
            "yearBuilt" => "YearBuilt", //"lname",
            "salePrice" => "SalePrice", //"company",
            "landSqFt" => "Land Sq Ft", //"urbanization",
            "address" => "Address", //"address",
            "city" => "City", //"city",
            "zip" => "Zip", //"zip",
            "state" => "State", //"state",
            "granter" => "Granter", //"granter(seller)",
            "siteAddress" => "SiteAddress", //"siteaddress",
            "bedRoom" => "BedRooms", //"bedrooms",
            "bath" => "BathRooms", //"baths",
            "actualSqFT" => "ActualSqFt", //"ActualSqFt"
        ],
        "BRO" => [
            "preSortDate" => "PreSortte", //"presortdate",
            "saleDate" => "SaleDate", //"mname",
            "contactID" => "ContactID", //"contactid",
            "name" => "Owner", //"fname",
            "yearBuilt" => "YearBuilt", //"lname",
            "salePrice" => "SalePrice", //"company",
            "landSqFt" => "LandSqFt", //"urbanization",
            "address" => "Address", //"address",
            "city" => "City", //"city",
            "zip" => "Zip", //"zip",
            "state" => "State", //"state",
            "granter" => "SalesIn", //"salesin",
            "legalLine" => "LegalLine", //"legalline",
            "siteAddress" => "SiteAddress", //"address concatinated",
            "bedRoom" => "BedRooms", //"beds",
            "bath" => "BathRooms", //"baths",
            "actualSqFT" => "Sq Ft", //"Sq Ft"
        ],
        "HIL" => [
            "preSortDate" => "PreSortDate", //"presortdate",
            "saleDate" => "SaleDate", //"saledate",
            "contactID" => "ContactID", //"contactid",
            "address" => "Address", //"address",
            "city" => "City", //"city",
            "zip" => "Zip", //"zip",
            "state" => "State", //"state",
            "siteAddress" => "SiteAddress", //"siteaddress",
            "bedRoom" => "BedRooms", //"bedrooms",
            "bath" => "BathRooms", //"bathrooms",
            "yearBuilt" => "YearBuilt", //"yearbuilt",
            "salePrice" => "SalePrice", //"saleprice",
            "name" => "Company", //"company",
            "landSqFt" => "TotalHeatedAreaSqFt", //"totalheatedAreasqft",
            "actualSqFT" => "TotalGrossareaSqFt", //"totalgrossareasqft",
            "granter" => "TotalBuildingValue", //"totalbuildingvalue",
            "legalLine" => "Neighbourhood", //"neighbourhood",
            "propertyType" => "PropertyType", //"propertytype",
            "siteCity" => "SiteCity", //"sitecity",
            "siteZip" => "SiteZip", //"sitezip"
        ],
        "LAC" => [
            "preSortDate" => "PresortDate", //
            "saleDate" => "Sale Date", //
            "contactID" => "ContactID", //
            "siteAddress" => "Site Address",
            "address" => "Address", //
            "city" => "City", //
            "zip" => "Zip", //
            "state" => "State", //
            "bedRoom" => "Beds", //
            "bath" => "1/2 Baths", //
            "yearBuilt" => "Year Built", //            
            "salePrice" => "Sale Price", //
            "name" => "Company", //
            "landSqFt" => "Land Size (Square Feet)", //
            "actualSqFT" => "Heated Area", //
            "legalLine" => "Full Baths", //
            "propertyType" => "Detailed Property Type"//
        ],
        "SAR" => [
            "preSortDate" => "PresortDate", //
            "saleDate" => "Last Sale Date", //
            "contactID" => "ContactID", //
            "name" => "Company", //
            "siteAddress" => "Site Address",
            "address" => "Address", //
            "city" => "City", //
            "zip" => "Zip", //
            "state" => "State", //
            "bedRoom" => "Beds", //
            "bath" => "Baths", //
            "yearBuilt" => "Year Built", //            
            "salePrice" => "Last Sale Price", //            
            "landSqFt" => "Living Area", //
            "actualSqFT" => "Gross Building Area", //
            "legalLine" => "Taxable Value" //         
        ]
    ];
    public $purposes = [
        "state" => "State Order",
        "rState" => "R State Order",
        "fictitious" => "Fictitious Order",
        "proDoc" => "Property Document Order",
        "annual" => "Annaul Compliance Order"
    ];

}
